#Data Contract Destino.
target:
  table: sales_transactions
  schema:
    transaction_id: BIGINT
    customer_id: TEXT
    customer_id_hash: TEXT
    product_id: BIGINT
    quantity: INT
    sale_date: DATE
  primary_key:
    - transaction_id
  
  #Campo incremental segun destino
  incremental_field: timestamp   # <--- columna configurable para incremental load

#Data Contract origen, columnas obligatorias
required_source_columns:
  - transaction_id
  - customer_id
  - product_id
  - quantity
  - timestamp

#Transformation
column_mapping:
  timestamp: sale_date

#Data Quality
data_quality:
  quantity:
    gt: 0
  transaction_id:
    not_null: true

unique_constraints:
  - columns: [transaction_id]       # valida duplicados solo en estas columnas

#Seguridad/Encriptacion
security:
  encrypt_columns:
    - customer_id       # columna a cifrar con Fernet
  hash_columns:
    - customer_id       # columna a hashear con SHA256


control_table:
  name: etl_control
  schema:
    table_name: VARCHAR(255) PRIMARY KEY
    last_loaded_timestamp: TIMESTAMP
    last_run_id: VARCHAR(36)
    last_run_type: VARCHAR(20)
    updated_at: TIMESTAMP